### ISSUE TITLE
Autosave feature doesn't work in majors mask 4th and 0th day

### ISSUE THREAD

**Issue by TheTrueShadow** [Mr-Wiseguy/N64Recomp#18]
Not sure if this is a bug or not but the built-in autosave feature doesn't work on any glitched days like 4th day or 0th day

**Comment by Fondant** [comment]
im not sure that this repo is the best place to put issues specifically related to MM using the recomp, maybe post this over [here](https://github.com/Mr-Wiseguy/Zelda64Recomp/issues)

**Comment by TheTrueShadow** [comment]
Thank you
