### ISSUE TITLE
Subsystem (TransferPak, MemoryCard)

### ISSUE THREAD

**Issue by IngwiePhoenix** [Mr-Wiseguy/N64Recomp#28]
Hello there!

I have yet to read the source in full, but the first thing that immediately came to my mind was support for accessories such as the TransferPak for Pokémon Stadium. Sure, it'll be perfectly fine for single-player stuff, but the real fun starts with the addition of players' own cartridges and pokémon. So, I wanted to ask about compatibility with that.

This is a super neat project - digging into this source will be very interesting!

Kind regards,
Ingwie

**Comment by Mr-Wiseguy** [comment]
System functionality is provided by the runtime implementation a given recompilation project uses. For example, the Zelda64Recomp project uses a runtime I wrote called [ultramodern](https://github.com/Mr-Wiseguy/Zelda64Recomp/tree/dev/ultramodern). It'd be possible to add support for those peripherals in some way to the runtime if other projects used ultramodern, but that's unrelated to the recompiler itself.

**Comment by Lucoshi** [comment]
It gave me an idea for a GB Tower esque mode for many rareware games
