### ISSUE TITLE
How to compile Smash 64 on Steam Deck?

### ISSUE THREAD

**Issue by Papyrusty** [Mr-Wiseguy/N64Recomp#29]
It's my first time using Cmake on steam deck. A step-by-step guide would be nice! The instructions are too vague so IDK what to do

**Comment by Fondant** [comment]
if your looking to just compile the recompilers i could help with that but you may want to wait for a bit so that mr-wiseguy has time to build a [MVP example](https://github.com/Mr-Wiseguy/N64Recomp/issues/17#issuecomment-2106400499)

**Comment by Mr-Wiseguy** [comment]
This repo is not the place to ask for recompilations of specific games.
