### ISSUE TITLE
AKI games/

### ISSUE THREAD

**Issue by shyguy85** [Mr-Wiseguy/N64Recomp#34]
could this work with the AKI wcw/wwf games?

**Comment by thetahiransari** [comment]
e AKI wcw/wwf games could potentially work with the online gaming platforms mentioned in the search results, such as Poki and CrazyGames, where you can find a variety of free online games. These platforms offer a wide selection of games in different genres like action, sports, puzzles, and more, which could complement the AKI wcw/wwf games. While the specific compatibility of the AKI wcw/wwf games with these online platforms is not explicitly mentioned in the search results, you can explore the games available on Poki and CrazyGames to see if they align with the style and gameplay of the AKI wcw/wwf games.

**Comment by Mr-Wiseguy** [comment]
Recompiling a specific game is something to be done by a user of this tool. I don't know if a given game works until somebody tries it.
