### ISSUE TITLE
how to run on MAC? a simple downloadable .exe and .dmg file?

### ISSUE THREAD

**Issue by fisforfaheem** [Mr-Wiseguy/N64Recomp#40]
its hard to to do when u r not a hardcore dev

**Comment by AngheloAlf** [comment]
Building the recompiler on Mac works fine as long as you know how to use cmake, but you wouldn't be able to use it to get an N64 game running on Mac.

This repository hosts the tool that allows recompiling an N64 game, this repository does not contain any game specific stuff. You may be thinking about the https://github.com/Mr-Wiseguy/Zelda64Recomp/ repository, which currently does not have Mac support yet.
