### ISSUE TITLE
System requirments

### ISSUE THREAD

**Issue by GizmoTheGreen** [Mr-Wiseguy/N64Recomp#47]
Would be really nice if there was a Requirments list for running ports made with this..

Not as in cpu or gpu horsepower but what does it compile to require as far as libraries and API? instructions sets like MMX or SSE2?
Does it need win10/11? vbruntimes? is it a software renderer or opengl or dx...9?12? vulkan?

Would love to run some good old games on some Retro PC with win98se or XP on.

**Comment by miqumi** [comment]
All that is upto the developer who ports the games.
